### ISSUE TITLE
The ACPCore package react-native-acpcore version 2.0.0 is giving issues in iOS.

### ISSUE THREAD

**Issue by HemanthSurimaniLegato** [adobe/react-native-acpcore#123] opened 2021-11-11 17:17 UTC
Hello All,

Need help from anyone to fix the below ACPCore library issue in iOS app. 

Issue : After installed the react-native-acpcore version 2.0.0 in React Native application, the iOS app is showing the below error when I try to build the app.

My Xcode version is 12.4. My iOS app is Swift based app.

'ACPCore.h' file not found with <angled> include; use "quotes" instead

Versions:
    "@adobe/react-native-acpcore": "^2.0.0",
     "react": "17.0.1",
    "react-native": "0.64.2",
      pods version : 1.11.2

Screen shot is for the reference.
Any help on this issue is great for us to fix that.
@infil00p 
 

Thanks 
Hemanth Surimani
<img width="1048" alt="Screenshot 2021-11-11 at 2 49 17 PM" src="https://user-images.githubusercontent.com/94131233/141340529-3742d79d-3eb1-4544-bb6b-d600689ca2a5.png">

**Comment by lohithananda** [comment] 2021-11-22 13:49
Same Issue As Above.

Issue : After installed the react-native-acpcore version 2.0.0 in React Native application, the iOS app is showing the below error when I try to build the app.

Versions:
"@adobe/react-native-acpcore": "^2.0.0",
"react": "16.13.1",
"react-native": "0.63.4",
pods version : 1.11.2

**Comment by shtomar-adb** [comment] 2021-11-22 18:02
Hi @lohithananda ,

From the screenshot, it looks like the dependency ACPCore is found.
How are you linking the modules to your app?
If the modules are linked by RN auto link, please also ensure that you run cd ios/ && pod install in your app.

**Comment by lohithananda** [comment] 2021-11-24 11:12
@shtomar-adb i have tried linking and run pod install still no luck.

**Comment by shtomar-adb** [comment] 2021-11-24 18:31
Hi @lohithananda 

Could you verify that under the Pods project, ACPCore is present.
Pods Project -> Pods -> ACPCore.

Also please follow the installation instructions here:
https://github.com/adobe/react-native-acpcore#installation

**Comment by meenunegi** [comment] 2022-04-04 11:08
Hi,

I am still facing the above issue with react-native-acpcore version 2.0.0 in iOS build.

Any solution for this?

**Comment by yangyansong-adbe** [comment] 2022-04-18 19:46
@meenunegi  Can you take a look at this Swift article: https://developer.apple.com/documentation/swift/imported_c_and_objective-c_apis/importing_objective-c_into_swift and add a bridging header file to your Swift app?

**Comment by yangyansong-adbe** [comment] 2022-05-17 17:54
Close this inactive issue.

**Comment by amankalra4** [comment] 2022-09-19 15:47
Facing the same issue in react-native

**Comment by cacheung** [comment] 2022-09-19 16:06
@amankalra4 Do you have "use_frameworks!" in your Podfile?  If so, please remove it and see if it works for you.

Thanks,
Calise

**Comment by amankalra4** [comment] 2022-09-19 17:23
@cacheung 
Tried removing "use_native_modules!" from the Podfile and then ran pod install again.
But this didn't solve the error.

**Comment by cacheung** [comment] 2022-09-19 17:46
@amankalra4 
Do you see ACPCore is present?
Pods Project -> Pods -> ACPCore.

And your iOS is an Objective-C or a swift app?

**Comment by amankalra4** [comment] 2022-09-19 17:50
@cacheung 
Yeah, ACP Core is present in the pods folder.

And iOS is in Objective-C.

**Comment by amankalra4** [comment] 2022-09-19 18:00
I'm using these pods in the podfile

pod 'ACPAnalytics'
pod 'ACPUserProfile'
pod 'ACPCore'
pod 'ACPMobileServices'

@cacheung

**Comment by cacheung** [comment] 2022-09-19 19:51
@amankalra4 
It seems like your app is not finding the path in the pod.
Can you check your Xcode > project > Build Settings > Header Search Paths.  Set it to

**Comment by amankalra4** [comment] 2022-09-20 05:44
@cacheung 
Tried adding the same, but that didn't work.
To be precise, the package that shows the error is: "RCTACPCore"

Having organisation policies, wont be able to share the file,
but the podfile contains these pods from adobe packages

pod 'ACPAnalytics'
pod 'ACPUserProfile'
pod 'ACPCore'
pod 'ACPMobileServices'

If required, I can help with few more things

**Comment by cacheung** [comment] 2022-09-20 17:04
You don't need to add ACP pod info in the App Podfile.  It will be installed when you have @adobe/react-native-acpcore installed.

https://github.com/adobe/react-native-acpcore#installation
Can you delete the Pods folder from your app and remove below lines from your Podfile
 pod 'ACPCore'
 pod 'ACPUserProfile'
 pod 'ACPMobileServices'

cd toYourApp
npm install @adobe/react-native-acpcore
cd ios/ && pod install

Check your app's package.json
Do you see @adobe/react-native-acpcore there?  What version you have?
And what react-native version you are using?

**Comment by amankalra4** [comment] 2022-09-20 17:46
Tried removing the same, but that didn't work.

Yes, "@adobe/react-native-acpcore" is present in package.json

Version of "@adobe/react-native-acpcore" is: "^2.0.2"
Version of "react-native" is: "0.66.1"

**Comment by amankalra4** [comment] 2022-09-20 17:49
Files that give error are present in "**RCTACPCore**" in "**node_modules**":

RCTACPLifecycle.m
RCTACPIdentityDataBridge.h
RCTACPIdentity.m
RCTACPCoreDataBridge.h

**Comment by cacheung** [comment] 2022-09-21 00:41
What exactly the errors you saw, same as the one at the top of the issue?  ACPCore.h file not found with angled include use quotes instead?

I can't reproduce the error with the test app in this repo:
[pod file](https://github.com/adobe/react-native-acpcore/blob/main/sample/ACPCoreSampleApp/ios/Podfile)
It uses react native version  "0.64.2".  I can't  upgrade it to 0.66.1 due to too many compatibility dependencies. 

Can you provide a skeleton sample app with your setup and we can take a look?
Let us know if you prefer to log a ticket through the customer care, and we can share the file offline.

**Comment by amankalra4** [comment] 2022-09-21 07:54
Yes, it's the same error mentioned as above.

But its not only for ACPCore, but its for below mentioned headers as well:

```
'ACPCore.h' file not found with <angled> include; use "quotes" instead
'ACPLifecycle.h' file not found with <angled> include; use "quotes" instead
'ACPIdentity.h' file not found with <angled> include; use "quotes" instead
```

Since, we are developing for iOS, so I've attached files related to iOS only.

Can you please have a look, if required, I can share more info.
[Sample FIles.zip](https://github.com/adobe/react-native-acpcore/files/9614253/Sample.FIles.zip)

**Comment by cacheung** [comment] 2022-09-21 09:04
Trying to make the Podfile similar to the sample app, for your Podfile, can you try to update the below lines
 use_react_native!(:path => config["reactNativePath"])
 use_flipper!()
 
Deleted the Podfile.lock, and then run pod install

If you can provide a simple sample app which can demonstrate the issue, that would be helpful to debug. 

Thanks,
Calise

**Comment by amankalra4** [comment] 2022-09-21 18:05
Tried doing the same, but that didn't work.

@cacheung By sample app, do you mean should I share a new project with these packages integrated?

**Comment by cacheung** [comment] 2022-09-21 19:03
@amankalra4  What system you are using for your development?  Is it a Mac with M1?  
If you could provide a simple sample app with the same source structure and config for reproducing this issue.  We can run it on our side and look into.  You can prepare the app without running npm install.

**Comment by amankalra4** [comment] 2022-09-22 17:53
@cacheung Yes its Mac with M1 chip.
But one of my team mates tries running on his system with Intel chip as well, there also same error was faced.

Yes sure, will prepare a project and share that. But if you could provide some other insights, that would be really helpful.

**Comment by cacheung** [comment] 2022-09-22 19:45
@amankalra4 We saw an issue on another app which happened only on M1 chip, but the error was different than yours.  
We will wait for your project.

**Comment by amankalra4** [comment] 2022-10-25 06:50
Hi @cacheung,
With latest version I was not able to resolve the issue.
So, I had to downgraded the version of the package and that resolved the issue.

**Comment by cacheung** [comment] 2022-10-25 17:56
Hi @amankalra4, I can't reproduce this in our sample app, so not able to make progress with your issue.  I am going to close this ticket.  If you are able to provide us more info, please feel free to ask on the forum again.

**Closed by cacheung** 2022-10-25 17:56 UTC

**Comment by NehaCloverBay** [comment] 2023-08-10 13:53
> Hi @cacheung, With latest version I was not able to resolve the issue. So, I had to downgraded the version of the package and that resolved the issue.

Hey @amankalra4 I'm facing the same issue, what is the version number which you have downgraded ?
