### ISSUE TITLE
Unable to send track message 

### ISSUE THREAD

**Issue by maoesx** [adobe/react-native-acpcore#47] opened 2019-10-18 06:03 UTC
### Expected Behaviour
After setup ACPCore andACPAnalytic, by calling the trackState and trackAction function, the app is except to send out track message to the Adobe serve.

### Actual Behaviour
The adobe server didn't get any track message, I couldn't oberve any track message been sending out from my local with proxy tool (Charles) either.

#### Steps to Reproduce
1. Follow the documentation to setup ACPCore and ACPAnalytic
2. ACPCore.setLogLevel(ACPMobileLogLevel.VERBOSE);
    ACPCore.configureWithAppId("my environment id");
    ACPLifecycle.registerExtension();
    ACPIdentity.registerExtension();
    ACPSignal.registerExtension();
    ACPAnalytics.registerExtension();
    ACPCore.start();
3. Call trackState and trackAction function with data
4. See the track function was successfully triggered with console output
5. Check the adobe server and proxy tool

I also tried the ACPCoreSample, didn't observed any track message been sent out either.

#### Platform and Version
Platform and Version
Node v10.15.0
Npm 6.4.1
react-native-cli: 2.0.1
react-native: 0.59.3

**Comment by nporter-adbe** [comment] 2019-10-18 07:34
Please provide the adobe logs while observing this issue.

**Comment by nporter-adbe** [comment] 2019-10-18 07:44
What’s the log output when you make a A
trackAction Or trackState call?

**Comment by maoesx** [comment] 2019-10-18 14:11
I put console.log in ACPCore.js line 196 (trackAction function) and line 211(trackState function) and make sure those two functions was properly triggered.

**Comment by nporter-adbe** [comment] 2019-10-18 15:27
Do you see logs such as `Analytics request sent with body..`? I'm not able to replicate your issue. Please share your logs (remove any references to your app id in the logs).

**Comment by maoesx** [comment] 2019-10-18 15:29
I didn't see any logs with "Analytics request sent with body", where shall I see them, in the console?

**Comment by nporter-adbe** [comment] 2019-10-18 15:30
Yes, please share your console logs  (remove any references to your app id in the logs before sharing).

**Comment by maoesx** [comment] 2019-10-18 16:13
I haven't oberserv any adobe related log in my console, is there suppose to be logs created when the library is init or trackState/Action firing?

**Comment by nporter-adbe** [comment] 2019-10-18 16:26
You should see logs related to the Adobe SDK on startup when you set `ACPCore.setLogLevel(ACPMobileLogLevel.VERBOSE);`. 

Here is a little sample of what the logs look like when I run the ACPCoreSample app:
```
2019-10-18 10:25:31.245743-0600 ACPCoreSample[64223:10400087] [AdobeExperienceSDK DEBUG <com.adobe.module.identity>]: Privacy opt-unknown: Suspend Identity database
2019-10-18 10:25:31.247047-0600 ACPCoreSample[64223:10400087] [AdobeExperienceSDK TRACE <DatabaseService>]: <ADBMobileSignals.sqlite> opened successfully
```

It sounds like your app isn't loading the native modules, see the trouble shooting guide: https://github.com/adobe/react-native-acpcore#trouble-shooting

To ensure the native code is being ran set breakpoints in `RCTACPCore.m`.

**Comment by maoesx** [comment] 2019-10-18 17:21
I think you are right, but I can't see any logs contain key word "adobe", I have 
```
    pod 'RCTACPCore', :path => '../node_modules/@adobe/react-native-acpcore'
    pod 'RCTACPAnalytics', :path => '../node_modules/@adobe/react-native-acpanalytics'
```
in my podfile and the pod install is successful.

I enter the RCTACPCore.m file in the node_modules and make changes in line 137 (not sure this is correct)

```
RCT_EXPORT_METHOD(trackAction: (nullable NSString*) action data: (nullable NSDictionary*) data) {

    [ACPCore trackAction:action data:data];
    [ACPCore log:ACPMobileLogLevelDebug tag:EXTENSION_NAME message:@"acpcore fire  trackAction"];
} 
```

and change 
`ACPCore.setLogLevel(ACPMobileLogLevel.DEBUG);`

but still didn't see any log.

**Comment by nporter-adbe** [comment] 2019-10-18 17:23
I'm guessing when you set a breakpoint in `RCT_EXPORT_METHOD(trackAction: (nullable NSString*) action data: (nullable NSDictionary*) data)` it doesn't fire?

I'm not sure what is unique to your project or how the SDK was installed to get into a state where React Native isn't loading the native modules.

**Comment by maoesx** [comment] 2019-10-18 17:26
Yeah I'm gonna to run the ACPCoreSample and see how does that work for me, do I need install ACPAnalytic to fire the trackState and trackAction?
Also am I setting the breakpoint in RCTACPCore.m correctly?

**Comment by nporter-adbe** [comment] 2019-10-18 17:27
You didn't make any mention that you set a break point, just that you added a line to log some output.

If you want to test trackState/action you'll need to use the Analytics sample app: https://github.com/adobe/react-native-acpanalytics/tree/master/sample/ACPAnalyticsSample

**Comment by maoesx** [comment] 2019-10-18 17:46
I'm have successfully run the ACPAnalyticsSample,here's the log output in my react native debug console:

```
Running application ACPAnalyticsSample ({
    initialProps =     {
    };
    rootTag = 31;
})
infoLog.js:16 Running application "ACPAnalyticsSample" with appParams: {"rootTag":31,"initialProps":{}}. __DEV__ === true, development-level warning are ON, performance optimizations are OFF
App.js:45 AdobeExperienceSDK IMPORT: ACPAnalytics = [object Object]
App.js:54 analytic start //my console.log
App.js:91 track state //my console.log
App.js:96 track action //my console.log
``` 

Still didn't see any AdobeExperienceSDK log.

**Comment by nporter-adbe** [comment] 2019-10-18 17:47
The logs are in the Xcode console, not the JS console.

**Comment by maoesx** [comment] 2019-10-18 17:55
Ohhhhh I see, in that case I do have AdobeExperienceSDK log in my app, here's the log:

```
2019-10-18 12:28:30.068581-0500 App[19392:1570678] [AdobeExperienceSDK DEBUG <TaskExecutor>]: System info services are required to set thread name
2019-10-18 12:28:30.072973-0500 App[19392:1570678] [AdobeExperienceSDK DEBUG <Core>]: Registered Configuration module
2019-10-18 12:28:30.080940-0500 App[19392:1571010] [AdobeExperienceSDK WARNING <ConfigurationDownloader>]: Failed to find cacheed config at "myEnvironment".json
2019-10-18 12:28:30.081996-0500 App[19392:1571010] [AdobeExperienceSDK DEBUG <com.adobe.module.configuration>]: Bundled configuration loaded. 
2019-10-18 12:28:30.100150-0500 App[19392:1571010] [AdobeExperienceSDK DEBUG <com.adobe.module.configuration>]: Shared state has been created for event #0 with data: {
2019-10-18 12:28:30.208476-0500 App[19392:1571139] [AdobeExperienceSDK DEBUG <com.adobe.module.identity>]: Privacy opt-unknown: Suspend Identity database
2019-10-18 12:28:30.220162-0500 App[19392:1571139] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Couldn't retrieve shared state for com.adobe.module.identity. Please make sure you have registered and configured the  extension properly based on the documentation.
2019-10-18 12:28:30.512123-0500 App[19392:1571140] [AdobeExperienceSDK ERROR <com.adobe.module.configuration>]: Unable to fetch config. Rolling back to previous configuration.
```

**Comment by nporter-adbe** [comment] 2019-10-18 18:03
Now when I call `ACPAnalytics.trackState(...);` I can see logs which indicate a hit is queued up. Depending on your `batchLimit` you may need to call `ACPAnalytics.sendQueuedHits();` to see the hits leave the device.
```
2019-10-18 12:01:16.168533-0600 ACPAnalyticsSample[72929:10472145] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Analytics Request Queued (ndh=1&c.&a.&AppID=ACPAnalyticsSample%201.0%20%281%29&CarrierName=%28null%29&DeviceName=x86_64&OSVersion=iOS%2013.0&Resolution=1242x2688&RunMode=Application&.a&mytest=state&.c&ce=UTF-8&cp=foreground&mid=75485004524108341524947131796655226898&pageName=state&t=00%2F00%2F0000%2000%3A00%3A00%200%20360&ts=1571421676)
2019-10-18 12:01:16.169597-0600 ACPAnalyticsSample[72929:10472145] [AdobeExperienceSDK TRACE <DatabaseService>]: QueryResult: <name> = ANALYTICS_HITS
2019-10-18 12:01:16.171574-0600 ACPAnalyticsSample[72929:10472145] [AdobeExperienceSDK TRACE <DatabaseService>]: QueryResult: <ID> = 1
```

**Comment by maoesx** [comment] 2019-10-18 18:04
Is it ACPCore.trackState or ACPAnalytic.trackState?

**Comment by nporter-adbe** [comment] 2019-10-18 18:04
Updated my comment.

**Comment by maoesx** [comment] 2019-10-18 18:13
I got a log 
`2019-10-18 13:06:38.454464-0500 App[21958:1619659] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Couldn't retrieve shared state for com.adobe.module.identity. Please make sure you have registered and configured the  extension properly based on the documentation.`

The steps I set it up is:
1. npm install @adobe/react-native-acpanalytics
2. react-native link @adobe/react-native-acpanalytics
3. cd ios/ && pod install
4.  ACPCore.setLogLevel(ACPMobileLogLevel.DEBUG);
    ACPCore.configureWithAppId("my app id");
    ACPLifecycle.registerExtension();
    ACPIdentity.registerExtension();
    ACPSignal.registerExtension();
    ACPAnalytics.registerExtension();
    ACPCore.start();

any steps I missed?

**Comment by nporter-adbe** [comment] 2019-10-18 18:14
That should be ok. What logs are generated when you call trackState?

**Comment by maoesx** [comment] 2019-10-18 18:16
It keep throwing the same log when I do trackState or trackAction:
`2019-10-18 13:14:47.755769-0500 App[21958:1619659] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Couldn't retrieve shared state for com.adobe.module.identity. Please make sure you have registered and configured the  extension properly based on the documentation.`

**Comment by nporter-adbe** [comment] 2019-10-18 18:18
If you don’t see analytics hits being queued up, then this is likely an issue with your config. I can’t help with this, I’d recommend contacting whoever maintains that’s mobile property or reach out to customer care.

**Comment by nporter-adbe** [comment] 2019-10-18 18:22
I’d also like to point out our docs suggest to init the SDK in native code. But I don’t think that’d fix this issue, but it might be worth a shot.

**Comment by maoesx** [comment] 2019-10-18 18:22
Yes, I got logs like 
`[AdobeExperienceSDK WARNING <ConfigurationDownloader>]: Failed to download config from https://assets.adobedtm.com/"my app id".json
2019-10-18 13:19:16.282545-0500 BMAApp[21958:1619659] [AdobeExperienceSDK ERROR <com.adobe.module.configuration>]: Unable to fetch config. Rolling back to previous configuration.
2019-10-18 13:19:16.282749-0500 BMAApp[21958:1619659] [AdobeExperienceSDK WARNING <EventHub(AMSEventHub)>]: Unable to create or update shared state for com.adobe.module.configuration with version 10.`

I got the app id from my someone who running the adobe analytic suite for us, so you mean there is certain config need to be done? Is there any documentation about what need to be config?

**Comment by maoesx** [comment] 2019-10-18 18:24
Thanks for point it out, will try native init

**Comment by nporter-adbe** [comment] 2019-10-18 18:24
What happens when you visit https://assets.adobedtm.com/"my app id".json in your browser?

**Comment by maoesx** [comment] 2019-10-18 18:24
empty page shows "File not found."

**Comment by nporter-adbe** [comment] 2019-10-18 18:25
That’s the issue, contact your analytics admin and let them know the config is not published.

**Comment by maoesx** [comment] 2019-10-18 18:28
Thanks! Do you have any reference about how to config and publish?

**Comment by nporter-adbe** [comment] 2019-10-18 18:29
This might help: https://aep-sdks.gitbook.io/docs/getting-started/create-a-mobile-property

**Comment by nporter-adbe** [comment] 2019-10-18 19:44
Closing this for now, as it appears to be an issue with the remote config not being published.

**Closed by nporter-adbe** 2019-10-18 19:44 UTC

**Comment by maoesx** [comment] 2019-10-22 17:28
Thanks for the refererence, I have talked to our analytic admin and he have published the config file, I can see logs like
`2019-10-22 12:21:09.232940-0500 BMAApp[49029:2297781] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Analytics Request Queued (ndh=1&cid.&AVID.&as=0&id=40A7F7ADACEB46C9-2025DA04D2649920&.AVID&.cid&c.&a.&AppID=BMAApp%201.0%20%281.0%29&CarrierName=%28null%29&DeviceName=x86_64&OSVersion=iOS%2013.1&Resolution=828x1792&RunMode=Application&action=Barcode%20Scan-initiate&privacy.&mode=unknown&.privacy&.a&.c&aid=40A7F7ADACEB46C9-2025DA04D2649920&ce=UTF-8&cp=foreground&mid=28298515807486133088091466241253339303&pageName=App%201.0%20%281.0%29&pe=lnk_o&pev2=AMACTION%3ABarcode%20Scan-initiate&t=00%2F00%2F0000%2000%3A00%3A00%200%20300)`
in the xcode console. 
To make sure that is not a queue issue, I added `ACPAnalytics.sendQueuedHits();` after every trakcState and trackAction method, I can see `2019-10-22 12:21:09.229805-0500 BMAApp[49029:2297610] [AdobeExperienceSDK DEBUG <com.adobe.module.analytics>]: Kick all hits event was sent` in the xcode console.
But I still can not find any message been send out throgh Charles, and our analytic is not getting any message either.

**Comment by nporter-adbe** [comment] 2019-10-22 17:32
Does Charles show any of your device network activity? Could it be an issue with a VPN? At this point your hits are queued and you should see logs indicating `Analytics request was sent with body..`

**Comment by maoesx** [comment] 2019-10-22 17:39
Yes, it does show all the other activities.
I can only see logs like `Analytics Request Queued`, but haven't find any log with `Analytics request was sent...`

**Comment by nporter-adbe** [comment] 2019-10-22 17:58
I see hits go out with my app ID in the analytics sample app and not able to reproduce this issue. I'm guessing this is another config issue, double check your analytics configuration that your server address is valid and that everything looks correct.

Also check if you see any warning or error logs.

If you are sure you have everything configured properly and are correctly implementing analytics based on the [docs](https://aep-sdks.gitbook.io/docs/using-mobile-extensions/adobe-analytics), please reach out to [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket.

**Comment by maoesx** [comment] 2019-10-22 19:04
I runned the Analyticsample app and see these logs:
`2019-10-22 13:58:43.409244-0500 ACPAnalyticsSample[50463:2347149] [AdobeExperienceSDK WARNING <com.adobe.module.analytics>]: Analytics is not configured, the track request will be dropped.
2019-10-22 13:59:33.983633-0500 ACPAnalyticsSample[50463:2347035] [] nw_connection_get_connected_socket [C172] Client called nw_connection_get_connected_socket on unconnected nw_connection
2019-10-22 13:59:35.988426-0500 ACPAnalyticsSample[50463:2347035] [] nw_socket_handle_socket_event [C173.1:1] Socket SO_ERROR [61: Connection refused]`
so after the config json is published, is there any other config need to be done?

**Comment by nporter-adbe** [comment] 2019-10-22 19:05
I'd reach out to your analytics admin and let them know Analytics is not configured. If you need to please reach out to [customer care](https://helpx.adobe.com/marketing-cloud/contact-support.html) and open a ticket.

**Comment by maoesx** [comment] 2019-10-22 19:07
Thanks, I will go check with him.
