### ISSUE TITLE
Does v2.0.1 provide Android 12 support.

### ISSUE THREAD

**Issue by e-pradeep** [adobe/react-native-acpcore#129] opened 2022-07-08 07:51 UTC
According to latest updates "Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12"

When targeting to Android 12, getting build error: 

Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.

These are the activity inside the manifest without exported tag
•   com.adobe.marketing.mobile.FullscreenMessageActivity" 
•   com.adobe.marketing.mobile.LocalNotificationHandler"

react-native-acpcore- v2.0.1

https://developer.android.com/google/play/requirements/target-sdk#:~:text=Starting%20in%20August%202022%2C%20new,behavioral%20changes%20in%20Android%2012

**Comment by cacheung** [comment] 2022-07-11 21:26
Hi,

Thanks for the report.  We are evaluating this.

Best Regards,
Calise

**Comment by cacheung** [comment] 2022-07-19 17:20
@e-pradeep Thanks for your patience.  We are planning to fix this in the next release.  Will keep you updated when it is ready.

**Comment by nidheeshsundar07** [comment] 2022-07-20 07:27
@cacheung  Can you confirm when will be the next release date??

**Comment by cacheung** [comment] 2022-07-20 19:14
Hi @e-pradeep We plan to release at the beginning of August.

**Comment by cacheung** [comment] 2022-07-25 23:35
@e-pradeep We just released react-native-acpcore- v2.0.2, the andrdoid:exported attributes are updated in the extension's AndroidManifest file.  Thanks again for your report.

**Comment by archcorsair** [comment] 2022-07-30 02:27
@cacheung I'm experiencing an issue, maybe related to this topic, sorry if it is unrelated. (If it ends up being unrelated I will open a new issue).
Working on upgrading react native to `0.68` from `0.67` and one of the upgrades is gradle from `4.x.x` -> `7.x.x`
Cannot build currently, seeing this error (cleaned for readability)
```
> Task :app:processDebugMainManifest FAILED
Execution optimizations have been disabled for task ':app:processDebugMainManifest' to ensure correctness due to the following reasons:

- Gradle detected a problem with the following location: '/app/node_modules/@adobe/react-native-acpanalytics/android/build/intermediates/merged_manifest/debug/AndroidManifest.xml'.

Reason:
Task ':app:processDebugMainManifest' uses this output of task ':@adobe_react-native-acpanalytics:processDebugManifest' without declaring an explicit or implicit dependency.

This can lead to incorrect results being produced, depending on what order the tasks are executed.
Please refer to https://docs.gradle.org/7.3.3/userguide/validation_problems.html#implicit_dependency for more details about this problem.

**Comment by cacheung** [comment] 2022-08-02 07:26
Hi @archcorsair,  this is a different issue. 
Can you open an issue in https://github.com/adobe/react-native-acpanalytics with the details,  we will take a look.

Thanks,
Calise

**Comment by cacheung** [comment] 2022-08-04 17:19
@archcorsair I looked into the issue you reported.  People saw this issue after upgrading to Grade 7.  It doesn't seem like the root cause is from react-native acpcore or acpanalytics. 
This is a discussion I saw from Stackoverflow: [link](https://stackoverflow.com/questions/70817001/react-native-execution-optimizations-have-been-disabled-for-tasks-sudden-error)
Please let us know if you have any other question.

I am going to close this issue which is originally reported for AndroidManifest 'android:exported' attribute.
You can open a new issue for further discussion.

**Closed by cacheung** 2022-08-04 17:19 UTC
